app:
  debug: true
  host: "0.0.0.0"
  port: 5000

database:
  uri: "sqlite:///../db/dt.sqlite"
  track_modifications: false
  commit_on_teardown: true

setting:
  path: 'D:\\TEST'


user:
  name: 'caozh'

